package model;


import java.util.Random;

import model.Tiles.MeadowGrass;
import model.Tiles.TallGrass;
import model.Tiles.TreeBottomLeft;
import model.Tiles.TreeBottomRight;
import model.Tiles.TreeLeft;
import model.Tiles.TreeRight;
import model.Tiles.MidTreeTopLeft;
import model.Tiles.MidTreeTopRight;
import model.Tiles.TreeTopLeft;
import model.Tiles.TreeTopRight;
import model.Tiles.Water;
import model.Tiles.WaterBottom;
import model.Tiles.WaterBottomLeft;
import model.Tiles.WaterBottomRight;
import model.Tiles.WaterLeft;
import model.Tiles.WaterRight;
import model.Tiles.WaterTop;
import model.Tiles.WaterTopLeft;
import model.Tiles.WaterTopRight;
/**
 * This class designs the Meadow map for the game
 *
 */
public class Meadow {
private Tile[][] meadow;

/**
 * calls the required functions (makeMedow() and addRockSmash();)
 */
    public Meadow(){
	    makeMeadow();
	    addRockSmash();
    }
    /**
	 * designs the desert map using a 2-D array
	 */
    private void makeMeadow(){
    	meadow = new Tile[][] {
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight()},
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(),		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(),	new TreeBottomRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight()},
    			{new TreeLeft(),		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new WaterTopLeft(), 	new WaterTop(), 		new WaterTop(), 		new WaterTop(), 		new WaterTopRight(), 	new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new WaterBottomLeft(), 	new WaterBottom(), 		new WaterBottom(), 		new WaterBottom(), 		new WaterBottomRight(), new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight()},
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(),		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight()},
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new WaterTopLeft(), 	new WaterTop(), 		new WaterTop(), 		new WaterTop(), 		new WaterTop(), 		new WaterTop(),			new WaterTop(), 		new WaterTopRight(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new WaterLeft(), 		new Water(), 			new Water(), 			new Water(), 			new Water(), 			new Water(), 			new Water(), 			new WaterRight(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight()},
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new WaterLeft(), 		new Water(), 			new Water(), 			new Water(), 			new Water(), 			new Water(), 			new Water(), 			new WaterRight(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new TreeBottomLeft(),	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new MeadowGrass(),		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new WaterLeft(), 		new Water(), 			new Water(), 			new Water(), 			new Water(), 			new Water(), 			new Water(), 			new WaterRight(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight()},
    			{new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new WaterBottomLeft(), 	new WaterBottom(), 		new WaterBottom(), 		new WaterBottom(), 		new WaterBottom(), 		new WaterBottom(), 		new WaterBottom(), 		new WaterBottomRight(), new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new WaterTopLeft(), 	new WaterTop(), 		new WaterTop(), 		new WaterTop(),  		new WaterTop(), 		new WaterTopRight(), 	new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass()},
    			{new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new WaterLeft(), 		new Water(), 			new Water(), 			new Water(),  			new Water(), 			new WaterRight(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass()},
    			{new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new WaterLeft(), 		new Water(), 			new Water(), 			new Water(),  			new WaterBottom(), 		new WaterBottomRight(), new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass()},
    			{new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new WaterLeft(), 		new Water(), 			new Water(), 			new WaterRight(),  		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass()},
    			{new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new WaterLeft(), 		new Water(), 			new Water(), 			new WaterRight(),  		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass()},
    			{new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new WaterLeft(), 		new Water(), 			new Water(), 			new WaterRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass()},
    			{new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new WaterTopLeft(), 	new WaterTop(), 		new WaterTop(), 		new WaterTop(), 		new WaterTop(), 		new WaterTop(), 		new WaterTop(), 		new WaterTopRight(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new WaterBottomLeft(), 	new WaterBottom(), 		new WaterBottom(), 		new WaterBottomRight(), new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),  	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass()},
    			{new TreeTopLeft(), 	new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new WaterBottomLeft(), 	new WaterBottom(), 		new WaterBottom(), 		new WaterBottom(),		new WaterBottom(), 		new WaterBottom(), 		new WaterBottom(),		new WaterBottomRight(), new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight()},
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TallGrass(),	new TallGrass(),	new TallGrass(), 	new TallGrass(), 	new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(),		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TallGrass(), 	new TallGrass(), 	new TallGrass(), 	new TallGrass(), 	new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight()},
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TallGrass(), 	new TallGrass(), 	new TallGrass(),	new TallGrass(), 	new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TallGrass(), 	new TallGrass(), 	new TallGrass(), 	new TallGrass(), 	new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new TallGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight()},
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight()},
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new TreeTopLeft(), 		new TreeTopRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight()},
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeLeft(), 		new TreeRight(), 		new TreeLeft(),			new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight(), 	new MidTreeTopLeft(), 	new MidTreeTopRight()},
    			{new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight(), 		new TreeLeft(), 		new TreeRight()},
    			{new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 		new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new MeadowGrass(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight(), 	new TreeBottomLeft(), 	new TreeBottomRight()},
    	};
    }
    /**
	 * sets the rock smash ability of the character
	 */
    private void addRockSmash(){
    	Random randomGenerator = new Random();
		   
   	    int rockSmashC = randomGenerator.nextInt(4) + 4;
   	    int rockSmashR = randomGenerator.nextInt(10) + 8;
   	    
   	    meadow[rockSmashR][rockSmashC].setHasRockSmash(true);
   	    
    }
    /**
	 * returns the meadow array of tiles
	 * @return meadow
	 */
    public Tile[][] getMeadow(){
    	return meadow;
    }
}
